arcalot/arcalot-round-table

ART_MEMBERS.md

Signed-off-by: Jared O'Connell <46976761+jaredoconnell@users.noreply.github.com>
I added my account to the members list.
---

Add Jared to ART members

---

ART_MEMBERS.md

Added myself as a new member to the Round Table. When do I get my armament?
---

new member Marko Karg added to the Round Table

---

ART_MEMBERS.md

Signed-off-by: Peter Portante <peter.a.portante@gmail.com>
Looking to join as a lowly knight.
---

Coming to the table

---

ART_MEMBERS.md

Adding jdowni000 to members list

---

ART_MEMBERS.md

This PR adds @engelmi as a member. 
---

added @engelmi as member

---

ART_MEMBERS.md

Signed-off-by: Sanja Bonic <86982064+sanjacodes@users.noreply.github.com>
---

Removing myself

---

art-decisions/proposals/2022-10-26-standardize-on-poetry.md

Reformatted the proposal for readability.
---

Reformat a bit for readability in review

---

art-decisions/proposals/2022-10-26-standardize-python-formatting.md

Add details to formatting proposal.
---

Revision to include details

---

art-decisions/proposals/2022-10-26-standardize-on-poetry.md

Add proposal to standardize on poetry for python projects.
---

add poetry proposal

---

art-decisions/RECORD.md

Ratifying decision to standardize python projects on poetry
---

Ratifying decision to standardize python projects on poetry

---

ART_MEMBERS.md

Signed-off-by: Ryan Smith <ryan.d.smith.106@gmail.com>
Added myself to the ART members file.
---

Add Ryan to ART_MEMBERS

---

ART_MEMBERS.md

add HubertStefanskit to ART members

---

ART_MEMBERS.md

Signed-off-by: Tullio Sebastiani <tsebastiani@users.noreply.github.com>
---

Adding Tullio Sebastiani to ART

---

ART_MEMBERS.md

@mkarg75 has asked to be removed from the ART as he will no longer have the time to participate in the community.
---

Removing Marko Karg from the ART

---

art-decisions/RECORD.md

Ratify for ART proposal PR #30 
---

ratify PR #30

---

art-decisions/RECORD.md

ratify pr #31

---

ART_MEMBERS.md

Demote Peter P to member

---

ART_MEMBERS.md
art-decisions/RECORD.md

ratify pr #32

---

ART_MEMBERS.md

I hereby resign my position in the ART, effective April 28, 2023.
---

Removing myself from the ART

---

art-decisions/proposals/2023-10-09-matt-chair-nomination.md

Nominating Matt Leader for chair position
---

Matt Leader for chair

---

ART_MEMBERS.md

Make myself available for reviews as well as future ARCA development.
---

add Dave Butenhof to members

---

ART_MEMBERS.md

Add myself to the members list.
---

Add Webb to members

---

ART_MEMBERS.md

updating Hubert's github account ID
---

updating Hubert's github account ID

---

ART_MEMBERS.md

Peter has indicated that he no longer has the bandwidth to participate in the Arcalot community. Thanks for your help while you've been involved, @portante !
---

removing peter from the round table

---

ART_MEMBERS.md

Updating ART membership based on requests and non-activity.
---

Member maintenance

---

art-decisions/proposals/2024-06-03-retire-arcalog.md

Proposal to retire the Arcalog project from the Arcalot org.
---

propose retiring arcalog

---

art-decisions/RECORD.md

ratify PR #45

---

art-decisions/proposals/2024-06-07-arcaflow-roadmap.md

Adopt an Arcaflow roadmap

---

art-decisions/RECORD.md

ratify PR #48

---

ART_MEMBERS.md

Adding myself to the ART members list.
---

Add Ravi to ART-members list

---

art-decisions/RECORD.md

Ratifies the changes from the charter revision.
---

Ratify PR #53

---

art-decisions/RECORD.md

Adding a missing decision to the record.
---

Ratify #29
